// <auto-generated />
using System;
using LootManagerApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LootManagerApi.Migrations
{
    [DbContext(typeof(LootManagerContext))]
    [Migration("20230319071829_UpdateDefaultDataAddCreatedAT")]
    partial class UpdateDefaultDataAddCreatedAT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LootManagerApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 3, 19, 7, 18, 29, 46, DateTimeKind.Utc).AddTicks(5720),
                            Email = "test@test.com",
                            FullName = "test",
                            PasswordHash = "$2a$11$8cw6miPq.y9410.HdRfgNe/A7hRaBqE3wN8U9r6X6Oea2PC7bLbxq"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 3, 19, 7, 18, 29, 210, DateTimeKind.Utc).AddTicks(4037),
                            Email = "jerry@aol.com",
                            FullName = "Jerry Seinfeld",
                            PasswordHash = "$2a$11$ivRZ9Bm.YVBZYP3w/X106ejyTT5yb3OGjtRvl6svCZ8SyO2BFrlGG"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 3, 19, 7, 18, 29, 369, DateTimeKind.Utc).AddTicks(7551),
                            Email = "George.Costanza@aol.com",
                            FullName = "George Costanza",
                            PasswordHash = "$2a$11$Wqv1pwiucLVCGilHBApO/e8AmrgIGSEk5FQRS7YuphNuLXA3en7l2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 3, 19, 7, 18, 29, 533, DateTimeKind.Utc).AddTicks(188),
                            Email = "Elaine.Benes@aol.com",
                            FullName = "Elaine Benes",
                            PasswordHash = "$2a$11$zkE2ClSYi1guBfnhDhcyg.jkOyVUddBXnQBjCtUBH8Yw8RcA6DzS."
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 3, 19, 7, 18, 29, 695, DateTimeKind.Utc).AddTicks(8199),
                            Email = "Cosmo.Kramer@aol.com",
                            FullName = "Cosmo Kramer",
                            PasswordHash = "$2a$11$ncYGmTSNl723NLjuFjkII.NzasIPhqHLC4sL.Kzss8U3sjyrhykHu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
