// <auto-generated />
using System;
using LootManagerApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LootManagerApi.Migrations
{
    [DbContext(typeof(LootManagerContext))]
    [Migration("20230501150725_NewModelWithLocationId")]
    partial class NewModelWithLocationId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElementImage", b =>
                {
                    b.Property<int>("ElementsId")
                        .HasColumnType("int");

                    b.Property<int>("ImagesId")
                        .HasColumnType("int");

                    b.HasKey("ElementsId", "ImagesId");

                    b.HasIndex("ImagesId");

                    b.ToTable("ElementImage");
                });

            modelBuilder.Entity("ImageInfoSheet", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("int");

                    b.Property<int>("InfoSheetsId")
                        .HasColumnType("int");

                    b.HasKey("ImagesId", "InfoSheetsId");

                    b.HasIndex("InfoSheetsId");

                    b.ToTable("ImageInfoSheet");
                });

            modelBuilder.Entity("LootManagerApi.Entities.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InfoSheetId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InfoSheetId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1127),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 1,
                            LocationId = 1,
                            Name = "Admin Fig",
                            Type = "Figurine",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1131),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 1,
                            LocationId = 2,
                            Name = "User Fig",
                            Type = "Figurine",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1135),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 1,
                            LocationId = 3,
                            Name = "Cont Fig",
                            Type = "Figurine",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1137),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 2,
                            LocationId = 1,
                            Name = "Admin Manga",
                            Type = "Manga",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1139),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 2,
                            LocationId = 2,
                            Name = "User Manga",
                            Type = "Manga",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1141),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 2,
                            LocationId = 3,
                            Name = "Cont Manga3",
                            Type = "Manga",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1143),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 3,
                            LocationId = 1,
                            Name = "Admin Comic",
                            Type = "Comic",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1145),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 3,
                            LocationId = 2,
                            Name = "User Comic",
                            Type = "Comic",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1147),
                            Description = "Description of the element",
                            Grade = "An excellent condition.",
                            InfoSheetId = 3,
                            LocationId = 3,
                            Name = "Cont Comic",
                            Type = "Comic",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("LootManagerApi.Entities.InfoSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WikiArticle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InfoSheets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorSignature = "The Contributor",
                            BarCode = "3 037920 02133 1",
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1066),
                            Designation = "Figurine",
                            Reference = "Fig-ref_01",
                            UserId = 3,
                            WikiArticle = "Small statue depicting a popular culture character."
                        },
                        new
                        {
                            Id = 2,
                            AuthorSignature = "The Contributor",
                            BarCode = "3 037920 02133 1",
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1071),
                            Designation = "Manga",
                            Reference = "Man-ref_01",
                            UserId = 3,
                            WikiArticle = "Japanese comic book."
                        },
                        new
                        {
                            Id = 3,
                            AuthorSignature = "The Contributor",
                            BarCode = "3 037920 02133 1",
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(1074),
                            Designation = "Comic",
                            Reference = "Com-ref_01",
                            UserId = 3,
                            WikiArticle = "Illustrated story in a book or magazine format, often featuring superheroes or humor."
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 24, 876, DateTimeKind.Utc).AddTicks(4427),
                            Email = "admin@loot.com",
                            FullName = "admin",
                            PasswordHash = "$2a$11$Rynkn9zKmLah3kioQ0xeseh2ATp9Ky67dh7gK/7///887rOXpMHei",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 86, DateTimeKind.Utc).AddTicks(4866),
                            Email = "user@loot.com",
                            FullName = "user",
                            PasswordHash = "$2a$11$UYUMuTGj69gLh5OvbMlvKO4o4tgKYSZqRqEpdna/beA3DF7IvUJBy",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 285, DateTimeKind.Utc).AddTicks(9671),
                            Email = "contributor@loot.com",
                            FullName = "contributor",
                            PasswordHash = "$2a$11$UvjA8imhhLgS2eo7HQW/sOAL8JVY/C/UNCj.O8xOhTtGyC/fXIyNO",
                            Role = 2
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.DefaultLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("DefaultLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LocationId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            LocationId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Indice")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfShelves")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Furnitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(659),
                            Indice = 1,
                            LocationId = 7,
                            Name = "Admin Furniture",
                            NumberOfShelves = 1,
                            RoomId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(663),
                            Indice = 1,
                            LocationId = 8,
                            Name = "User Furniture",
                            NumberOfShelves = 1,
                            RoomId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(665),
                            Indice = 1,
                            LocationId = 9,
                            Name = "Cont Furniture",
                            NumberOfShelves = 1,
                            RoomId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Indice")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(521),
                            Indice = 1,
                            LocationId = 1,
                            Name = "Admin's Main House",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(524),
                            Indice = 1,
                            LocationId = 2,
                            Name = "User's Main House",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(525),
                            Indice = 1,
                            LocationId = 3,
                            Name = "Cont's Main House",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(328),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(330),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(331),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(435),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(437),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(438),
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(469),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(470),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(472),
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(491),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(492),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(493),
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(505),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(507),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(508),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Indice")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShelfId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("ShelfId");

                    b.HasIndex("UserId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(956),
                            Indice = 1,
                            LocationId = 13,
                            Name = "Admin Position",
                            ShelfId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(960),
                            Indice = 1,
                            LocationId = 14,
                            Name = "User Position",
                            ShelfId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(962),
                            Indice = 1,
                            LocationId = 15,
                            Name = "Cont Position",
                            ShelfId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("Indice")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(587),
                            HouseId = 1,
                            Indice = 1,
                            LocationId = 4,
                            Name = "Admin Room",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(589),
                            HouseId = 2,
                            Indice = 1,
                            LocationId = 5,
                            Name = "User Room",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(592),
                            HouseId = 3,
                            Indice = 1,
                            LocationId = 6,
                            Name = "Cont Room",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("Indice")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPositions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Shelves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(870),
                            FurnitureId = 1,
                            Indice = 1,
                            LocationId = 10,
                            Name = "Admin Shelf",
                            NumberOfPositions = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(873),
                            FurnitureId = 2,
                            Indice = 1,
                            LocationId = 11,
                            Name = "User Shelf",
                            NumberOfPositions = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 1, 15, 7, 25, 286, DateTimeKind.Utc).AddTicks(875),
                            FurnitureId = 3,
                            Indice = 1,
                            LocationId = 12,
                            Name = "Cont Shelf",
                            NumberOfPositions = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ElementImage", b =>
                {
                    b.HasOne("LootManagerApi.Entities.Element", null)
                        .WithMany()
                        .HasForeignKey("ElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootManagerApi.Entities.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImageInfoSheet", b =>
                {
                    b.HasOne("LootManagerApi.Entities.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootManagerApi.Entities.InfoSheet", null)
                        .WithMany()
                        .HasForeignKey("InfoSheetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootManagerApi.Entities.Element", b =>
                {
                    b.HasOne("LootManagerApi.Entities.InfoSheet", "InfoSheet")
                        .WithMany("Elements")
                        .HasForeignKey("InfoSheetId");

                    b.HasOne("LootManagerApi.Entities.logistics.Location", "Location")
                        .WithMany("Elements")
                        .HasForeignKey("LocationId");

                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("Elements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoSheet");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.InfoSheet", b =>
                {
                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("InfoSheets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.DefaultLocation", b =>
                {
                    b.HasOne("LootManagerApi.Entities.logistics.Location", "Location")
                        .WithOne("DefaultLocation")
                        .HasForeignKey("LootManagerApi.Entities.logistics.DefaultLocation", "LocationId");

                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithOne("DefaultLocation")
                        .HasForeignKey("LootManagerApi.Entities.logistics.DefaultLocation", "UserId");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Furniture", b =>
                {
                    b.HasOne("LootManagerApi.Entities.logistics.Location", "Location")
                        .WithOne("Furniture")
                        .HasForeignKey("LootManagerApi.Entities.logistics.Furniture", "LocationId");

                    b.HasOne("LootManagerApi.Entities.logistics.Room", "Room")
                        .WithMany("Furnitures")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("Furnitures")
                        .HasForeignKey("UserId");

                    b.Navigation("Location");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.House", b =>
                {
                    b.HasOne("LootManagerApi.Entities.logistics.Location", "Location")
                        .WithOne("House")
                        .HasForeignKey("LootManagerApi.Entities.logistics.House", "LocationId");

                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("Houses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Location", b =>
                {
                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("Locations")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Position", b =>
                {
                    b.HasOne("LootManagerApi.Entities.logistics.Location", "Location")
                        .WithOne("Position")
                        .HasForeignKey("LootManagerApi.Entities.logistics.Position", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootManagerApi.Entities.logistics.Shelf", null)
                        .WithMany("Positions")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("Positions")
                        .HasForeignKey("UserId");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Room", b =>
                {
                    b.HasOne("LootManagerApi.Entities.logistics.House", "House")
                        .WithMany("Rooms")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootManagerApi.Entities.logistics.Location", "Location")
                        .WithOne("Room")
                        .HasForeignKey("LootManagerApi.Entities.logistics.Room", "LocationId");

                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("Rooms")
                        .HasForeignKey("UserId");

                    b.Navigation("House");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Shelf", b =>
                {
                    b.HasOne("LootManagerApi.Entities.logistics.Furniture", "Furniture")
                        .WithMany("Shelves")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootManagerApi.Entities.logistics.Location", "Location")
                        .WithOne("Shelf")
                        .HasForeignKey("LootManagerApi.Entities.logistics.Shelf", "LocationId");

                    b.HasOne("LootManagerApi.Entities.User", "User")
                        .WithMany("Shelves")
                        .HasForeignKey("UserId");

                    b.Navigation("Furniture");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LootManagerApi.Entities.InfoSheet", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("LootManagerApi.Entities.User", b =>
                {
                    b.Navigation("DefaultLocation");

                    b.Navigation("Elements");

                    b.Navigation("Furnitures");

                    b.Navigation("Houses");

                    b.Navigation("InfoSheets");

                    b.Navigation("Locations");

                    b.Navigation("Positions");

                    b.Navigation("Rooms");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Furniture", b =>
                {
                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.House", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Location", b =>
                {
                    b.Navigation("DefaultLocation");

                    b.Navigation("Elements");

                    b.Navigation("Furniture");

                    b.Navigation("House");

                    b.Navigation("Position");

                    b.Navigation("Room");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Room", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("LootManagerApi.Entities.logistics.Shelf", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
